spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "646609229988-u5rorv92gaj6sp4g4t161776dfh7abli.apps.googleusercontent.com"
            clientSecret: "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"
            redirectUri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
              - profile
  redis:
    host: localhost
    port: 6379
#    password: Optional, if Redis requires a password

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:
    admin: han2041126@gmail.com
jwt:
  key:
    secret: 001mainprojectwithskeyletsgoforitwecandoit
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

file:
  root:
    dir : /home/ssm-user/imag

resource:
  handler: /admin/post/image/**
  location: file:///D:/imgUpload/

image:
  upload:
    path: /home/ssm-user/imag

#    dir: C:\Users\MEcmp\Desktop\Main_Proj\sampleImgPath #임시로 업로드 이미지 저장하는 디렉토리

