spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: deploy
---

spring:
  datasource:
    url: jdbc:mysql:main001.ctmvpylzede6.ap-northeast-2.rds.amazonaws.com:23306/main001
    username: david
    password: 001mainproject
    driver-class-name: com.mysql.cj.jdbc.Drvier
#    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    open-in-view: false
  sql:
    init:
      data-locations: classpath:db/* #{classpath:article.sql, import.sql} # 경로 변경