cloud:
  aws:
    s3:
      bucket: ${BUCKNAME} #버킷 이름
    credentials:
      access-key: ${S3ACCESSKEY}
      secret-key: ${S3SECRETKEY}
    region:
      static: ${REGIONSTATIC}
    stack:
      auto: false