spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    open-in-view: false
  sql:
    init:
      data-locations: classpath:db/* #{classpath:article.sql, import.sql}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "646609229988-u5rorv92gaj6sp4g4t161776dfh7abli.apps.googleusercontent.com"
            clientSecret: "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"
            redirectUri: "http://localhost:8080/login/oauth2/code/google"
#            EC2에 올릴 때는 http://ec2-3-36-117-214.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google 로 변경해야함.
            scope:
              - email
              - profile
  redis:
    host: localhost
    port: 6379
#    password: Optional, if Redis requires a password

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:
    admin: han2041126@gmail.com
jwt:
  key:
    secret: 001mainprojectwithskeyletsgoforitwecandoit
  access-token-expiration-minutes: 10000
  refresh-token-expiration-minutes: 10000

file:
  root:
    dir : C:\Users\MEcmp\Desktop\Main_Proj\sampleImgPath\

resource:
  handler: /admin/post/image/**
  location: file:///D:/imgUpload/

image:
  upload:
    path: C:\Users\MEcmp\Desktop\Main_Proj\sampleImgPath\

#  dir: C:\Users\MEcmp\Desktop\Main_Proj\sampleImgPath #임시로 업로드 이미지 저장하는 디렉토리
# /home/ssm-user/imag

